name: Deploy to Server

on:
  push:
    branches:
      - master  # Modify this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # Choose your preferred runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Write SSH Private Key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy code to server
        run: |
           scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./PythonScripting/src/ subrat@20.172.195.131:/home/subrat/script
        # Alternatively, you can use rsync, FTP, or other methods for file transfer
